### ISSUE TITLE
Can't access the Google Drive link

### ISSUE THREAD

**Issue by hfangcat** [spaceml-org/FireCLR-Wildfires#1]
Hi,

Thanks for your contribution to releasing the training dataset, evaluation dataset, and pretrained models! 

When I clicked on the link, it said I don't have access to that, is it because the datasets are still in preparation?

Yours Sincerely,
Heng

**Comment by zhang-beichen** [comment]
Hi Heng, thanks for reporting this issue. The datasets were ready, but there were some issues with granting access to the Google Drive folder. We are working on addressing them, but if you want the datasets sooner, please DM me. I will be able to share them with you.

Best,
Beichen

**Comment by previtus** [comment]
Hi Heng,
I have updated the links, they should be now public - please check if you can access them.

Best,
Vit

**Comment by hfangcat** [comment]
@previtus @bzhang9683 Thanks a lot for your help! I just checked and I can access them now!
